Update packaging-sfdx-ci-master.yml
Kommentert ut logikk som oppdaterer sfdx-project.json og commit'er denne.

diff --git a/.github/workflows/packaging-sfdx-ci-master.yml b/.github/workflows/packaging-sfdx-ci-master.yml
--- a/.github/workflows/packaging-sfdx-ci-master.yml
+++ b/.github/workflows/packaging-sfdx-ci-master.yml
@@ -83,32 +83,32 @@ jobs:
       - name: "Install new package version into test org"
         if: steps.extract-data-package-version-create.outputs.isSuccess
         run: "sfdx force:package:install --package ${{ steps.extract-data-package-version-create.outputs.packageVersionId }} -w 10 -b 10 -u integration-sandbox -r -k ${{ secrets.PACKAGE_KEY }}"
-
       # Update sfdx-project.json and README to use only latest package version
-      - name: "Update sfdx-project.json and README"
-        if: success() || (failure() && steps.package-version-create.outputs.isSuccess)
-        id: packaging-updater
-        uses: muenzpraeger/github-action-sfdx-packaging-updater@master
-
-      # Create commit message by extracting the latest version number from sfdx-project.json
-      - name: "Build commit message"
-        if: success() || (failure() && steps.packaging-updater.outputs.isSuccess)
-        id: build-commit-message
-        run: echo "::set-output name=message::(CI) Update package version"
-
-      # Remove auth files
-      - name: "Remove auth files"
-        if: always()
-        run: |
-          rm -f ./DEVHUB_SFDX_URL.txt
-          rm -f ./INTEGRATION_SANDBOX_SFDX_URL.txt
-
-      # Re-add changes back to source
-      - name: "Add new package version, updated sfdx-project.json and README to source"
-        if: (success() || failure()) && steps.packaging-updater.outputs.isSuccess
-        uses: Automattic/action-commit-to-branch@master
-        with:
-          branch: "master"
-          commit_message: ${{steps.build-commit-message.outputs.message}}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: "Update sfdx-project.json and README"
+      #   if: success() || (failure() && steps.package-version-create.outputs.isSuccess)
+      #   id: packaging-updater
+      #   uses: muenzpraeger/github-action-sfdx-packaging-updater@master
+      #
+      # # Create commit message by extracting the latest version number from sfdx-project.json
+      # - name: "Build commit message"
+      #   if: success() || (failure() && steps.packaging-updater.outputs.isSuccess)
+      #   id: build-commit-message
+      #   run: echo "::set-output name=message::(CI) Update package version"
+      #
+      # # Remove auth files
+      # - name: "Remove auth files"
+      #   if: always()
+      #   run: |
+      #     rm -f ./DEVHUB_SFDX_URL.txt
+      #     rm -f ./INTEGRATION_SANDBOX_SFDX_URL.txt
+      #
+      # # Re-add changes back to source
+      # - name: "Add new package version, updated sfdx-project.json and README to source"
+      #   if: (success() || failure()) && steps.packaging-updater.outputs.isSuccess
+      #   uses: Automattic/action-commit-to-branch@master
+      #   with:
+      #     branch: "master"
+      #     commit_message: ${{steps.build-commit-message.outputs.message}}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #
